### ISSUE TITLE
objects clickable

### ISSUE THREAD

**Issue by GioAlba** [molon/MLLayout#20]
Hello I would like to know how you can make the objects in the cells clickable.
In fact if I try to use a link in a label if I press it does not do anything.
thanks

**Comment by molon** [comment]
@GioAlba This library is MLLayout not MLLabel. Do you enter a wrong place?

**Comment by GioAlba** [comment]
I've put a link in a comment. I used TTTAttributedLabel library for commentLabel to determine hyperlinks
If I click on a hyperlink, nothing happens.
Thank you

**Comment by molon** [comment]
@GioAlba According to the description, I think the issue is be provided in wrong place. 

If links in cells cant be clickable, it is usually because of that a cell gesture prevents it.
The solution like this : https://github.com/molon/MLLabel/blob/master/Example/MLLabel/ViewControllers/ListNoNibTableViewCell.m#L74-L88

If your scene is not same with this. please give me a demo to help you solve it. :)

**Comment by GioAlba** [comment]
Thanks fix problem!
